Adds SQS snippet for SQSBatchResponse
aws-samples/serverless-snippets pull request #117
Opened 2024-01-15 19:22 UTC by skamatka

Issue #, if available:

Description of changes:
Added SQS Snipnet for SQS Batch Response

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-25 17:49 UTC, falnyr requested changes
Hi @skamatka, thanks for your contribution. There are a few issues in the code that need addressing before we can merge this. Please check the subsequent comments for details. Feel free to reach out if you have any questions.

2024-01-25 17:49 UTC, falnyr commented on lambda-function-sqs-report-batch-item-failures/example.php
> +function lambda_handler(SQSEvent $event, Context $context) {
Based on the [Bref documentation](https://bref.sh/docs/runtimes/function#php-classes) You need to either return a function or a class for the handler. I suggest rewriting this handler into a class as it's more aligned to the other code samples for PHP.

2024-01-25 17:49 UTC, falnyr commented on lambda-function-sqs-report-batch-item-failures/example.php
> +
You are missing the vendor autoloader to load these classes.

2024-01-31 01:49 UTC, skamatka commented
I updated the code and tested it in my Isengard account. Please review the latest commit.

2024-02-01 09:11 UTC, falnyr approved these changes
Looks good to me, thanks for your contribution! 🙌

2024-02-06 00:50 UTC, merged