Added Rust implementation for msk-to-lambda integration
aws-samples/serverless-snippets pull request #210
Opened 2024-08-21 22:27 UTC by sachinh

*Issue #, if available:*

*Description of changes:*
Rust Implementation for MSK to Lambda integration

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-11 07:22 UTC, bnusunny commented on integration-msk-to-lambda/main.rs
> +    tracing_subscriber::fmt().json()
Use 'tracing::init_default_subscriber();' to replace this. This is a new function provided by Rust Runtime to simplify this part.

2024-10-11 07:24 UTC, bnusunny requested changes

2024-10-11 07:24 UTC, bnusunny commented on integration-msk-to-lambda/main.rs
> +         let record_text = record.value.as_ref().unwrap();
Don't use unwrap() here, use '?' to propergate the error.

2024-10-11 07:24 UTC, bnusunny commented on integration-msk-to-lambda/main.rs
> +         let message = std::str::from_utf8(&record_bytes).unwrap();
Again, don't use unwrap() here, use '?' to propergate the error.

2025-01-07 19:59 UTC, sachinh commented on integration-msk-to-lambda/main.rs
> +    tracing_subscriber::fmt().json()
Have made the changes in https://github.com/sachinh/serverless-snippets/commit/f1a38ad27e87d72523ff976f3b7f8c09827ce95a

2025-01-07 20:01 UTC, sachinh commented
@bnusunny Have made the code changes per your suggestions. Pl. review.

2025-01-10 07:35 UTC, bnusunny approved these changes
LGTM

2025-01-10 17:07 UTC, merged